### ISSUE TITLE
Any way to get Router for Linux?

### ISSUE THREAD

**Issue by UserwithnoUsername** [Beckhoff/AdsToJava#2]
Hello,
I have written a java Application with your Library. Is there any Way to put the Application on a Linux Server. Primarily the Problem is the Missing Router i think. Is there a Router planed for Java or do i have to write it on my own?

Regards Thomas

**Comment by vossjannik** [comment]
Hi @UserwithnoUsername,

unfortunately, this library does not currently have support for Linux systems.
However, here are a few resources that you might be able to build upon:
- https://github.com/Beckhoff/ADS
- https://github.com/Beckhoff/TF6000_ADS_DOTNET_V5_Samples/tree/main/Sources/RouterSamples

Best Regards, Jannik Voss

**Comment by vossjannik** [comment]
Hi @UserwithnoUsername,

Hi @martinste1n ,

I added Linux support using the "adslib.so" from https://github.com/Beckhoff/ADS/tree/master instead of the "TcAdsDll.dll", which as I mentioned, is not available on Linux.

There are some limitations+differences but it should be fine more most use-cases. I would call it a Beta. Details:
https://github.com/Beckhoff/AdsToJava/tree/linux?tab=readme-ov-file#status-of-the-linux-support

I would really appreciate feedback/contributions on this before merging it into the main branch.

Best Regards, Jannik Voss

**Comment by vossjannik** [comment]
FYI, I merged it into the main branch and added a CI build action (Ubuntu). The binaries are published as a release artifact called "linux-x64.zip".
