### ISSUE TITLE
Add a Release including libTcAdsDll.so for Debian or Ubuntu

### ISSUE THREAD

**Issue by martinste1n** [Beckhoff/AdsToJava#5]
Hi, first thank you for the great tool. We are currently trying to get it to run on a Ubuntu Machine / Docker Container. We invested quite some time to build the libTcAdsDll.so ourselves, yet failed to do so.

Would it be possible that you add a release, which contains a build version for Debian or Ubuntu?

Thanks in advance

**Comment by martinste1n** [comment]
Thank you very much for the fast reply! I will have a look at the resources you provided!

Best, Martin

**Comment by vossjannik** [comment]
Hi @martinste1n ,

the topic didn't let go of me yesterday.
I added Linux support using the "adslib.so" from https://github.com/Beckhoff/ADS/tree/master instead of the "TcAdsDll.dll", which as I mentioned, is not available on Linux.

There are some limitations+differences but it should be fine more most use-cases. I would call it a Beta. Details:
https://github.com/Beckhoff/AdsToJava/tree/linux?tab=readme-ov-file#status-of-the-linux-support

I would really appreciate feedback/contributions on this before merging it into the main branch.

Best Regards, Jannik Voss

**Comment by martinste1n** [comment]
Thank you very much 👍 that's really awesome.

Will give it a try next week and provide feedback!

Have a nice weekend!

Martin

**Comment by vossjannik** [comment]
@martinste1n FYI, I merged it into the main branch and added a CI build action (Ubuntu). The binaries are published as a release artifact called "linux-x64.zip".

**Comment by nicovitt** [comment]
I checked the released version and integrated it into our software environment (custom java PLC connector  deployed to Ubuntu VM). From what I can tell is that your provided solution works very well. 😄 

That is really awesome!

As @martinste1n wrote we were quite hard working on a solution for linux-based systems and I integrated your ADS repo but the problem was (at least what I can tell) that you can create a route in ADS on linux but AdsToJava does not know about the route. Was quite complicated to build and run on linux. 😄 

Your solution now works and we can communicate with Beckhoff PLCs. If I notice any issues I will contribute these.
